### ISSUE TITLE
Erreur de compilation

### ISSUE THREAD

**Issue by Nabil-renault** [r3dlight/keysas#30]
Bonjour, j'essaie d'installer keysas sur une machine debian 12 (avec environnement de bureau) or à l'exécution de la commande "make build" je rencontre ce message d'erreur : 

`
error: failed to run custom build command for `oqs-sys v0.7.2`

Caused by:
  process didn't exit successfully: `/home/debian/keysas/target/release/build/oqs-sys-5570d2ad47ae1f72/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/debian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/lib.rs:2172:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:21 : build] Erreur 101
`
Savez-vous quel pourrait être son origine ?

**Comment by r3dlight** [comment]
Bonjour,

Même si la v2.0 sera bientôt disponible, je vous conseille pour le moment de cloner la branch Develop comme suit:
`git clone --depth=1 --branch=Develop https://github.com/r3dlight/keysas.git`
Concernant votre problème de compilation, il semble que libclang.so ne soit pas installé. Avez-vous bien installé LLVM ?
`bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"`

**Comment by Nabil-renault** [comment]
Merci, effectivement j'avais oublié le sudo avant la commande `bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"`

**Comment by r3dlight** [comment]
Ok parfait :) 
Par ailleurs, si cela peut vous aider, je suis en train de mettre la documentation à jour (toujours en cours) [](https://keysas.fr/index.html)

**Comment by r3dlight** [comment]
Oui ce n'est pas encore très clair mais nous y travaillons :)

En fait, Keysas peut être installé de deux façons:
 - En mode passerelle filtrante entre deux réseaux (keysas-core uniquement)
 - En mode station blanche (installation complète)
 
La section "usage" correspond à une utilisation de keysas-core uniquement (mode passerelle de filtrage réseau). Cette section n'est donc pas très utile pour vous si vous souhaitez créer une station blanche. Toutefois la section "administration" vous intéressera puisqu'il s'agit du paramétrage du "keysas-core", le moteur de détection de la station blanche.
