### ISSUE TITLE
Problème lors de l'installation (mode station blanche)

### ISSUE THREAD

**Issue by Nabil-renault** [r3dlight/keysas#34]
Bonjour, c'est encore moi :) j'essaie de faire l'installation sur mon debian 12 en suivant la nouvelle documentation, à l'issue du `sudo make install` je regarde si les services sont bien activés, tout à l'air bon sauf pour keysas-transit et keysas-out : 
`keysas-transit.service - keysas-transit daemon
     Loaded: loaded (/etc/systemd/system/keysas-transit.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/keysas-transit.service.d
             └─security.conf
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-07-13 10:54:38 CEST; 1s ago
    Process: 50565 ExecStart=/usr/bin/keysas-transit -i ${SOCKET_IN} -o ${SOCKET_OUT} -s ${MAX_SIZE} -c ${CLAMAV_IP} -p ${CLAMAV_PORT} -r ${RULES} -t ${YARA_TIMEOUT} -a ${ALLOWED_TYPES} (code=exited, status=226>
   Main PID: 50565 (code=exited, status=226/NAMESPACE)
        CPU: 6ms`

● `keysas-out.service - keysas-out daemon
     Loaded: loaded (/etc/systemd/system/keysas-out.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/keysas-out.service.d
             └─security.conf
     Active: activating (auto-restart) (Result: signal) since Thu 2023-07-13 10:54:38 CEST; 1s ago
    Process: 50566 ExecStart=/usr/bin/keysas-out -o ${SOCKET_OUT} -g ${SAS_OUT} -c (code=killed, signal=SYS)
   Main PID: 50566 (code=killed, signal=SYS)
        CPU: 16ms
` Ensuite j'ai tout de même essayer l'installation de la partie frontend, npm i et npm run build se sont bien passé mais une fois que je copie tout les fichiers sur le repertoire de mon serveur apache2, seul une page blanche s'affiche et la console du navigateur me dit :
 `Uncaught TypeError: Erreur lors de la résolution du spécificateur de module « bootstrap ». Les spécificateurs de module relatifs doivent commencer par « ./ », « ../ » ou « / ».`

**Comment by r3dlight** [comment]
Bonjour,

Pouvez-vous redémarrer clamav-daemon et m'afficher l'output du démon keysas-transit comme suit svp : 
sudo systemctl restart clamav-daemon && sudo systemctl -fu keysas-transit

**Comment by Nabil-renault** [comment]
Oui, tout d'abord cela me sort `systemctl : option invalide -- 'u'`, puis sans le tiret 'u' j'obtiens : 
`keysas-transit.service - keysas-transit daemon
     Loaded: loaded (/etc/systemd/system/keysas-transit.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/keysas-transit.service.d
             └─security.conf
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-07-13 11:31:31 CEST; 177ms ago
    Process: 57447 ExecStart=/usr/bin/keysas-transit -i ${SOCKET_IN} -o ${SOCKET_OUT} -s ${MAX_SIZE} -c ${CLAMAV_IP} -p ${CLAMAV_PORT} -r ${RULES} -t ${YARA_TIMEOUT} -a ${ALLOWED_TYPES} (code=exited, status=226>
   Main PID: 57447 (code=exited, status=226/NAMESPACE)
        CPU: 6ms`

**Comment by r3dlight** [comment]
Il s'agissait de la commande journalctl (pardon faute de frappe :) :
`journalctl -fu keysas-transit`

**Comment by Nabil-renault** [comment]
Voici : `juil. 13 12:40:28 keysas-test (-transit)[58895]: keysas-transit.service: Failed at step NAMESPACE spawning /usr/bin/keysas-transit: No such file or directory
juil. 13 12:40:28 keysas-test systemd[1]: keysas-transit.service: Main process exited, code=exited, status=226/NAMESPACE
juil. 13 12:40:28 keysas-test systemd[1]: keysas-transit.service: Failed with result 'exit-code'.
juil. 13 12:40:31 keysas-test systemd[1]: keysas-transit.service: Scheduled restart job, restart counter is at 1197.
juil. 13 12:40:31 keysas-test systemd[1]: Stopped keysas-transit.service - keysas-transit daemon.
juil. 13 12:40:31 keysas-test systemd[1]: Started keysas-transit.service - keysas-transit daemon.
juil. 13 12:40:31 keysas-test (-transit)[58902]: keysas-transit.service: Failed to set up mount namespacing: /run/systemd/unit-root/var/local/transit: No such file or directory
juil. 13 12:40:31 keysas-test (-transit)[58902]: keysas-transit.service: Failed at step NAMESPACE spawning /usr/bin/keysas-transit: No such file or directory
juil. 13 12:40:31 keysas-test systemd[1]: keysas-transit.service: Main process exited, code=exited, status=226/NAMESPACE
juil. 13 12:40:31 keysas-test systemd[1]: keysas-transit.service: Failed with result 'exit-code'.
juil. 13 12:40:33 keysas-test systemd[1]: keysas-transit.service: Scheduled restart job, restart counter is at 1198.
juil. 13 12:40:33 keysas-test systemd[1]: Stopped keysas-transit.service - keysas-transit daemon.
juil. 13 12:40:33 keysas-test systemd[1]: Started keysas-transit.service - keysas-transit daemon.`

**Comment by r3dlight** [comment]
Pouvez-vous éditer le fichier suivant:
`sudo vim /etc/systemd/system/keysas-transit.service.d/security.conf`
et commenter la directive BindPaths=/var/local/transit avec un # comme suit:
#BindPaths=/var/local/transit
Puis lancez ensuite les commandes suivantes : 
`sudo systemctl daemon-reload`
`sudo systemctl restart clamav-daemon && sudo systemctl restart keysas`

**Comment by Nabil-renault** [comment]
Merci, les services sont désormais tous actifs. 
Concernant le problème avec le frontend en plus de l'erreur sus-mentionné il y a, dans la console du navigateur, (c'était déjà le cas avant l'application des modifs ci-dessus) une erreur 404 pour la requête `GEThttp://127.0.0.1/vite.svg`

**Comment by r3dlight** [comment]
Parfait, il s'agit d'un petit oubli de ma part, je vais patcher cela dans le code...
Pour le frontend, pouvez-vous créer à la main le répertoire comme suit : 
`sudo mkdir /var/lock/keysas`
et retester dans votre navigateur svp ?
Pouvez-vous également me confirmer que la homedir de votre vhost apache2 pointe bien vers le répertoire dans lequel se trouve les fichiers copiés ?

**Comment by Nabil-renault** [comment]
Ah je m'excuse, je me suis trompé de répertoire, j'ai copié tout ce qui se trouvait dans le répertoire keysas-frontend au lieu de sulement ce qui se trouve dans dist alors que c'est ce qui est écrit dans la documentation.

**Comment by r3dlight** [comment]
Aucun problème, j'espère que tout fonctionne :)

**Comment by Nabil-renault** [comment]
Je ne peux pas encore tester grand chose, quand j'essaie de lancer keysas-admin_2.0_amd64.AppImage (dont j'ai vérifier le hash e9779b61b81d7b638fdfccf3d6bc9835c796bfd5500f0c7095d6f6ded196d191), seul s'affiche le message : 
`keysas-admin: symbol lookup error: /tmp/.mount_keysaslnjTFO/usr/lib/libpango-1.0.so.0: undefined symbol: hb_ot_color_has_paint`.
J'aimerais aussi savoir comment configurer la fonction de transfert via le réseau et s'il est possible selon vous d'utiliser le protocol sftp pour le transfert (si oui je peux essayer de développer la fonctionnalité, juste dites moi avec quels fichiers travailler)

**Comment by r3dlight** [comment]
Sur quelle distribution tentez-vous de lancer l'appimage ? Nous ne l'avons testé que sur ArchLinux pour le moment. Avez-vous essayé le .deb ?
Concernant sftp, je n'ai pas testé mais n'hésitez pas à nous faire un retour, il s'agit surtout d'une question de permissions dans le répertoire d'entrée. Il n'y a pas vraiment lieu pour le moment de modifier le code à ce stade.

**Comment by Nabil-renault** [comment]
J'essaie sur une debian 12, j'ai peut-être louper l'info mais j'ai pas trouver de .deb
C'est noté pour le sftp je vous tiens au courant.
