### ISSUE TITLE
Installation KEYSAS-frontend et KEYSAS-Admin

### ISSUE THREAD

**Issue by MalcolmZeR** [r3dlight/keysas#41]
Bonjour,

Je m'excuse d'avance si je pose des questions "bêtes" mais je ne suis pas certain de bien tout comprendre.

J'ai installé KEYSAS via le .zip après avoir suivi les étapes précédentes de la documentation.
Tout est ok pour le CLAMAV et l'ensemble des services sont UP.

Pour le KEYSAS-FRONTEND, j'ai bien copier le contenu du dossier /dist dans le home_dir de NGINX. Par contre, j'ai une page blanche lorsque que j'essaye d'atteindre le site. Une idée ? C'est un problème de droit ?

Pour le Keysas-admin, j'ai suivi toutes les étapes et je bloque sur la dernière commande "cargo tauri build", j'obtiens le message suivant : 
`root@KEYSAS:/tmp/keysas/keysas-admin# cargo tauri build
error: no such command: `tauri`

        Did you mean `miri`?

        View all installed commands with `cargo --list`
`

En suivant la documentation, je suis un peu perdu. J'essaye de monter KEYSAS sur une debian12 Bookwarm et d'utiliser la fonctionnalité de décontamination des clés USB.
La machine sera hors-réseau et je souhaite juste passer des clés USB dedans pour analyse et décontamination. 
Au niveau de la doc, on est d'accord que je dois installer keysas, keysas-admin et frontend puis je passe directement à l'étape "Decontamination station for usb devices" ? ou pour ce que je veux faire, cela se passe dans un autre menu ?

Merci d'avance!
Malcolm

**Comment by r3dlight** [comment]
Bonjour,

> Je m'excuse d'avance si je pose des questions "bêtes" mais je ne suis pas certain de bien tout comprendre.
Aucune question n'est bête, c'est certainement la documentation doit être clarifiée.

> C'est un problème de droit ?
Probablement pas, pouvez-vous svp me donner le résultat de commandes suivantes:
`systemctl status keysas-io`
et 
`systemctl status keysas-backend`

Concernant, keysas-admin, un .deb est disponible ici : https://github.com/r3dlight/keysas/releases/download/v2.1/keysas-admin_2.1.0_amd64.deb

Si toutefois vous souhaitez le compiler vous-même (l'application ne sera pas signée), il vous manque certainement  tauri-cli : 
`cargo install tauri-cli`

Enfin, pour clarifier l'architecture :  
 - Keysas-admin doit être installé sur un ordinateur (Debian 12 + Desktop sans auto-mount des périphériques USB) dédié à l'administration des stations blanches à distance.
 - Keysas (un ensemble de démons + des binaires ELF) et keysas-frontend doivent être installés sur chaque station blanche.

**Comment by MalcolmZeR** [comment]
Bonjour,

Merci pour cette clarification.
Keysas n'est pas adapté à mon besoin finalement.

J'ai mal compris son fonctionnement au départ ; Je pensais que c'était une machine qui fonctionnait en autonomie, que je pouvais laisser en dehors de mon réseau sur laquelle j'allais connecter une clé usb pour analyse.

Et arrêtez-moi si je me trompe (car j'ai peut-être toujours rien compris), il me faut une debian 12 pour administrer mes stations blanches et des stations blanches sur lesquelles keysas-admin interviendra pour analyser, décontaminer des clés usb, accepter ou non les cles, etc......
Vous confirmez ?

Cordialement,
Malcolm

**Comment by r3dlight** [comment]
Non, les stations blanches, une fois enrollées par keysas-admin, sont autonomes. 
En gros, keysas-admin sert à créer la PKI qui vous permet d'enroller les stations blanches (pour la signature des fichiers analysés), à signer les périphériques USB de sortie (seuls les périphériques signés peuvent récupérer les fichiers analysés en sortie).
