### ISSUE TITLE
Prise en compte des fichiers temporaires de WinSCP ".filepart"

### ISSUE THREAD

**Issue by DAYELA** [r3dlight/keysas#47]
Bonjour, 
WinSCP upload les gros fichiers en créant un fichier temporaire avec l'extension ".filepart" sauf que Keysas n'ignore pas cette extension et fait passer du coup le fichier incomplet à travers le SAS interrompant l'upload.

Serait-il possible de rajouter une exception sur cette extension ?

**Comment by r3dlight** [comment]
Fixed on: https://github.com/r3dlight/keysas/commit/c80f9bf0d66827273cd686fc29e801ee748d3863

Please test and feed back.

**Comment by r3dlight** [comment]
I made a dedicated branch for this feature as I cannot ignore .filepart files for Keysas stations.
Anyway, you must pay attention using this feature: you should copy incoming files using winscp in a temporary directory then check if the transfert is completed before copying your files in SAS_IN directory.

**Comment by r3dlight** [comment]
Won't fix in Develop / main.
