### ISSUE TITLE
problem compiling Keysas library unstable

### ISSUE THREAD

**Issue by Thibautdbr** [r3dlight/keysas#53]
Good morning,
I have already managed to install keysas on debian 12 in the past, I wanted to try again but when compiling Keysas just after cloning the gitlab repository I was given this error:

error[E0658]: use of unstable library feature 'stdarch_x86_avx512'
  --> /root/.cargo/git/checkouts/curve25519-dalek-f168a129bf9b4917/1087aed/curve25519-dalek/src/backend/vector/ifma/field.rs:26:5
   |
26 |     _mm256_madd52lo_epu64(z.into(), x.into(), y.into()).into()
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
   = help: add `#![feature(stdarch_x86_avx512)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-05; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'stdarch_x86_avx512'
  --> /root/.cargo/git/checkouts/curve25519-dalek-f168a129bf9b4917/1087aed/curve25519-dalek/src/backend/vector/ifma/field.rs:25:9
   |
25 |     use core::arch::x86_64::_mm256_madd52lo_epu64;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
   = help: add `#![feature(stdarch_x86_avx512)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-05; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'stdarch_x86_avx512'
  --> /root/.cargo/git/checkouts/curve25519-dalek-f168a129bf9b4917/1087aed/curve25519-dalek/src/backend/vector/ifma/field.rs:34:5
   |
34 |     _mm256_madd52hi_epu64(z.into(), x.into(), y.into()).into()
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
   = help: add `#![feature(stdarch_x86_avx512)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-05; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'stdarch_x86_avx512'
  --> /root/.cargo/git/checkouts/curve25519-dalek-f168a129bf9b4917/1087aed/curve25519-dalek/src/backend/vector/ifma/field.rs:33:9
   |
33 |     use core::arch::x86_64::_mm256_madd52hi_epu64;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
   = help: add `#![feature(stdarch_x86_avx512)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-05; consider upgrading it if it is out of date

error[E0635]: unknown feature `stdsimd`
  --> /root/.cargo/git/checkouts/curve25519-dalek-f168a129bf9b4917/1087aed/curve25519-dalek/src/lib.rs:13:70
   |
13 | #![cfg_attr(all(curve25519_dalek_backend = "simd", nightly), feature(stdsimd))]
   |                                                                      ^^^^^^^

Some errors have detailed explanations: E0635, E0658.
For more information about an error, try `rustc --explain E0635`.
error: could not compile `curve25519-dalek` (lib) due to 5 previous errors

so I wanted to add #![feature(stdarch_x86_avx512)] at the beginning of the .rs files but nothing works, I still have the same error. Could you help me resolve this issue please.

**Comment by r3dlight** [comment]
Hi,

First, you should clone the Develop branch as the master branch is getting outdated.
Then, try this : 
`rustup update
cargo update`
and finally
`make build`

Keep me in touch

**Comment by Thibautdbr** [comment]
good evening, there was a problem with the new version curve25519-dalek updated on February 5, 2004, so I installed the old version of nightly and it worked
rustup install nightly-2024-02-03
rustup default nightly-2024-02-03
. See you later to find a stable solution for the new version of curve25519-dalek.
Thank you for your help

**Comment by r3dlight** [comment]
Hi,

Curve25519-dalek has been patched to address this issue.
No needs to install an older version of the compiler, a simple "cargo update" should be sufficient.
Cheers
