### ISSUE TITLE
connection problem between keysas-admin and keysas-station

### ISSUE THREAD

**Issue by arthur33974** [r3dlight/keysas#54]
Hello, I installed keysas on a DEBIAN 12 machine and just the keysas-admin application on another in the same network, I created my private and public keys and I entered them in the keysas-admin application , when exporting the public key to my keysas station it did not work. So I added the following lines at the end of the file sudoers to grant the keysas user the specified rights without requiring a password for the listed commands :

keysas ALL=(root) NOPASSWD: /usr/bin/keysas-sign
keysas ALL=(root) NOPASSWD: /usr/bin/keysas-manage-yubikey
keysas ALL=(root) NOPASSWD: /bin/systemctl reboot
keysas ALL=(root) NOPASSWD: /bin/systemctl poweroff
keysas ALL=(root) NOPASSWD: /usr/bin/apt update
keysas ALL=(root) NOPASSWD: /usr/bin/apt -y dist-upgrade
keysas ALL=(root) NOPASSWD: /usr/bin/sed -i s/

then I created .ssh because the logs told me that the keysas-admin machine could not find the authorized_keys file in the .ssh directory:

mkdir -p /home/keysas/.ssh
chmod 700 /home/keysas/.ssh

touch /home/keysas/.ssh/authorized_keys
chmod 600 /home/keysas/.ssh/authorized_keys

exporting my public key worked but now the keysas-admin application tells me that my keysas station is offline and I cannot Enroll my keysas station. I'm stuck, could you please help me thank you.

**Comment by r3dlight** [comment]
Hi,

Can you precise how your installation was made + which branch is used ?
I also advise you cloning the Develop branch as the master is getting a bit outdated.

Nevertheless, your installation seems broken as the sudo config for keysas user should be already installed (see https://github.com/r3dlight/keysas/blob/Develop/keysas-core/debian/keysas-sudoconfig).

Try updating the sudo config then re-export your public key and check that /home/keysas/.ssh/authorized_keys is correctly updated.
Keep us in touch.

**Comment by r3dlight** [comment]
No feedback, closing.
