### ISSUE TITLE
404 for download links in Raspberry Pi documentation

### ISSUE THREAD

**Issue by tutoduino** [r3dlight/keysas#55]
Issue in the documentation for [Raspberry](https://github.com/r3dlight/keysas/blob/main/documentation/user_documentation/raspberry.rst), both download links point to 404 :
[eysas-sd-v2.1]
https://keysas.fr/download/rasp/keysas-sd-v2.1.tar.gz
[keysas-admin-v2.1 (GNU/Linux)]
https://keysas.fr/download/keysas-admin/v2.1/keysas-admin_2.1_amd64.AppImage

**Comment by r3dlight** [comment]
Thanks for reporting.
This will be fixed in the next release :)
For now, downloads are available here https://github.com/r3dlight/keysas/releases
