### ISSUE TITLE
make build is broken

### ISSUE THREAD

**Issue by aaeMotoko** [r3dlight/keysas#56]
It link to the github https://github.com/mulkieran/loopdev who doesnt exist anymore, it seem to be https://github.com/mulkieran/loopdev-3 now.
Then the branch bump-bindgen-reduce-version doesnt exist in the new github.

Thank you for your work !

**Comment by r3dlight** [comment]
Hi, 
Thanks for reporting, 
This is already fixed in the Dev branch, so I advise you to clone this one if you wanna build by yourself.
The main will be fixed as soon as the new release is ready.
Cheers.
