### ISSUE TITLE
English is not working..needs updates

### ISSUE THREAD

**Issue by Werewolfman77** [r3dlight/keysas#60]
building front-end resulting in French interface
when i tried modifing the locale in main.js and also app.vue to be english , there were multiple error compiling 'AppWizard-en.vue'

for example:
<p>The operating system is based on a hardened GNU/Linux Debian 11 (codename: Bullseye). DHCP on on by default so you may want to check your network router to get back the IP address assigned to your Keysas at boot.**_</address>_**

at last it worked and the GUI was english but i can't add the station to the admin..it gives Error: cannot connect to the keysas station

i noted that:

keysas.service - keysas
     Loaded: loaded (/etc/systemd/system/keysas.service; enabled; preset: enabled)
     **### _Active: active (exited)_** since Fri 2024-04-26 15:08:52 EEST; 57min ago
    Process: 724 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 724 (code=exited, status=0/SUCCESS)
        CPU: 12ms

any guidelines ??

**Comment by Werewolfman77** [comment]
Managed to add the station by manually creating .ssh/authorized_keys on the station and editing it and adding the pub key of the admin

And enrolling worked

One more question though....any compiled version for the windows driver ?

**Comment by Werewolfman77** [comment]
It is working now
I just had to insert the signed key after the  non signed key

But the front end keeps saying dont remove the flash drive!!

That leaves to 1st question...any compiled driver for usb? Or compiling instructions??

Thanx for rhe great project

**Comment by r3dlight** [comment]
Hi, 
Glad that you finally made it work !
Yes, the AppWizard-en.vue is outdated and needs to be updated,  I'll patch it for the next release. To be honest, I think you're the first non-French speaking person to use it :) !
Regarding the windows driver, you need to buy an official certificate to sign the driver (unless your Windows is in dev mode).
Actually, you only need to load the keysas-firewall code into Microsoft Visual Studio 2022 with SDK and WDK version 10.0.22621.0 add your certificate and click to build the project.

**Comment by Werewolfman77** [comment]
Well...actually i am not english speaking either...i mean not my first language :)

As for french i had to use google translate to be able to read other issues comments to be able yo solve my issues...and it paid

Anyway...thanx for the nice project...and i will try to build the driver and see how it goes

**Comment by r3dlight** [comment]
You're welcome, I'm glad you find this project useful !
BTW, I've just pushed a first update of AppWizard-en.vue, feel free to review : 
https://github.com/r3dlight/keysas/blob/Develop/keysas-frontend/src/components/AppWizard-en.vue
