### ISSUE TITLE
Cannot connect th the Keysas station !

### ISSUE THREAD

**Issue by masterbalby2** [r3dlight/keysas#67]
Bonjour,

J'ai deux PC sous debian 12.
Un avec uniquement keysas-admin  et l'autre avec keysas et le frontend.
Les deux PC sont dans le même VLAN.

Sur le keysas-admin j'ai :
- généré ma clé publique et privé
- je les ai ajouté dans le menu "SSH CONFIGURATION"
- j'ai ensuite généré la clé IKPQPKI
- j'ai ajouté ma station en utilisant son IP

C'est au moment de l'enrôlement que je rencontre mon problème.
Lorsque je veux exporter ma clé publique SSH le message suivant apparaît :
```Error: cannot connect to the Keysas station!"```

Je ping bien la station distante.
Le ssh est fonctionnel avec l'user ```keysas``` et le mot de passe ```Changeme007```

Merci encore une fois pour votre aide.

**Comment by r3dlight** [comment]
Bonjour,

Assurez-vous que le répertoire /home/keysas/.ssh/ est bien présent sur la cible et exportez la clé publique SSH avant de faire l'enrollement.

**Comment by masterbalby2** [comment]
merci,

clef publique exportée et station enrôlée

tests toujours en cours

**Comment by Zedasix** [comment]
Même problème, impossible de partager les clés

**Comment by r3dlight** [comment]
Bonjour,

Le répertoire /home/keysas/.ssh/ est-il bien présent sur la station Keysas cible ?

**Comment by Zedasix** [comment]
Bonjour, oui tout est bien présent, j'ai refait une réinstallation au cas où et toujours pareil, après avoir suivi les instructions la clé publique n'est pas envoyée à cause d'une erreur de connexion.

**Comment by r3dlight** [comment]
Dans ce cas, il me faudrait les détails / logs de cette erreur de connexion.
Avez-vous essayez de copier simplement la clé SSH publique avec ssh-copy-id  ?

**Comment by Zedasix** [comment]
Alors j'ai réglé le problème par pur hasard, j'ai déjà partagé les clés via keysas-admin, ssh-copy et manuellement mais sans succès, j'ai fait un `ssh -i mykey keysas@192.168.xx.xx` et ça a fonctionné :)
